import { ArrowUpRight, Check, Leaf, MapPin } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { Breadcrumbs, ButtonLink, JourneyCTA, PageHero, SafariCard, SectionHeading, TextLink } from '../components/UI'
import { experiences, lodges, safaris } from '../lib/data'
import { NotFoundPage } from './Editorial'

export function ExperiencesPage() {
  return <><PageHero eyebrow="GO BEYOND THE ORDINARY" title="More than a safari." italic="A way of seeing the world." text="Extraordinary encounters. Small, unexpected joys. Follow the experiences that make you feel most alive." image="/images/kenya.jpg" /><section className="container section-pad experience-list">{experiences.map((experience, index) => <article className={`editorial-split ${index % 2 === 1 ? 'editorial-split-reverse' : ''}`} key={experience.slug}><Link className="editorial-split-image" to={`/experiences/${experience.slug}`}><img src={experience.image} alt={experience.shortTitle} loading="lazy" /><span>0{index + 1}</span></Link><div className="editorial-split-copy"><p className="eyebrow"><span />{experience.eyebrow}</p><h2>{experience.shortTitle}</h2><p>{experience.text}</p><TextLink to={`/experiences/${experience.slug}`}>Explore this experience</TextLink></div></article>)}</section><JourneyCTA /></>
}

export function ExperienceDetailPage() {
  const { slug } = useParams()
  const experience = experiences.find((item) => item.slug === slug)
  if (!experience) return <NotFoundPage />
  return <><PageHero eyebrow={experience.eyebrow} title={experience.title} text={experience.text} image={experience.image} /><Breadcrumbs items={[{ label: 'Experiences', to: '/experiences' }, { label: experience.shortTitle }]} /><section className="container section-pad editorial-split"><div className="editorial-split-copy"><p className="eyebrow"><span />THE FEELING IS EVERYTHING</p><h2>Experience it deeply.<br /><em>Remember it differently.</em></h2><p>{experience.text}</p><p>The right guide, a thoughtful pace, and a little room for the unexpected. That is how we turn an extraordinary experience into a deeply personal one.</p><ButtonLink to={`/plan-your-safari?experience=${encodeURIComponent(experience.shortTitle)}`}>Find your own way</ButtonLink></div><div className="experience-detail-notes"><Leaf size={39} strokeWidth={1} /><h3>Thoughtfully considered.</h3>{experience.details.map((detail) => <div key={detail}><Check size={17} /><p>{detail}</p></div>)}<span>Always guided by respect for people, wildlife, and place.</span></div></section><section className="related-section section-pad"><div className="container"><SectionHeading eyebrow="A LITTLE INSPIRATION" title="Make it part" italic="of your story." /><div className="safari-grid safari-grid-two">{safaris.filter((safari) => safari.category === experience.category).map((safari) => <SafariCard key={safari.slug} safari={safari} />)}</div></div></section><JourneyCTA /></>
}

export function LodgesPage() {
  return <><PageHero eyebrow="BEAUTIFUL PLACES TO BELONG" title="Stay somewhere" italic="that stays with you." text="Not just a bed for the night. A front-row seat to the landscape, a warm welcome, and a little space to call your own." image="/images/lodge.jpg" /><section className="container section-pad"><SectionHeading eyebrow="OUR KIND OF LUXURY" title="A sense of place." italic="A feeling of home." description="We find beauty in the thoughtful details. Explore the styles of stay we weave into our private journeys; individual properties are selected for your route and dates." /><div className="lodge-collection-grid">{lodges.map((lodge) => <article key={lodge.slug}><Link className="lodge-collection-image" to={`/lodges/${lodge.slug}`}><img src={lodge.image} alt={lodge.title} loading="lazy" /><span><MapPin size={12} />{lodge.location}</span><i><ArrowUpRight size={23} /></i></Link><div className="lodge-collection-body"><p className="eyebrow">{lodge.style}</p><Link to={`/lodges/${lodge.slug}`}><h3>{lodge.title}</h3></Link><p>{lodge.text}</p><TextLink to={`/lodges/${lodge.slug}`}>Step inside the feeling</TextLink></div></article>)}</div></section><section className="lodge-philosophy"><div className="container"><Leaf size={38} strokeWidth={.9} /><p className="eyebrow">WHAT MATTERS TO US</p><h2>The best luxury<br /><em>leaves room for the wild.</em></h2><p>We look for smaller places, genuine hospitality, and a real connection to the surrounding landscape. The stays pictured are inspiration for your journey, not a promise of a particular property. Your personal proposal names each lodge and explains why it belongs in your story.</p><TextLink to="/conservation">Our approach to thoughtful travel</TextLink></div></section><JourneyCTA /></>
}

export function LodgeDetailPage() {
  const { slug } = useParams()
  const lodge = lodges.find((item) => item.slug === slug)
  if (!lodge) return <NotFoundPage />
  return <><PageHero eyebrow={lodge.location} title={lodge.title} text={lodge.style} image={lodge.image} /><Breadcrumbs items={[{ label: 'Places to stay', to: '/lodges' }, { label: lodge.title }]} /><section className="container section-pad lodge-detail-layout"><div><p className="eyebrow"><span />FIND A LITTLE SPACE FOR YOURSELF</p><h2>Unpack. Exhale.<br /><em>You are here.</em></h2><p className="lead-copy">{lodge.text}</p><p>Your stay is part of the journey, not an afterthought. We consider the setting, the welcome, the rhythm of each day, and the feeling of returning after an extraordinary experience.</p><p>Exact properties are selected around your travel dates, route, and preferences. Share the comforts that matter to you, and we will help find the right fit.</p><ButtonLink to={`/plan-your-safari?stay=${lodge.slug}`}>Make room for this</ButtonLink></div><div className="lodge-features"><Leaf size={30} strokeWidth={1} /><h3>Little details. A big difference.</h3>{lodge.features.map((feature) => <div key={feature}><Check size={17} />{feature}</div>)}<p>Images and descriptions illustrate a style of stay. Your final proposal will confirm named properties and inclusions.</p></div></section><section className="related-section section-pad"><div className="container"><SectionHeading eyebrow="ANOTHER KIND OF BEAUTIFUL" title="A different place" italic="to make yourself at home." /><div className="lodge-related-grid">{lodges.filter((item) => item.slug !== lodge.slug).map((item) => <Link to={`/lodges/${item.slug}`} key={item.slug}><img src={item.image} alt={item.title} loading="lazy" /><div><span>{item.location}</span><h3>{item.title}<ArrowUpRight size={23} /></h3></div></Link>)}</div></div></section><JourneyCTA /></>
}
