import { ArrowUpRight, Compass, Leaf, MapPin, Sun } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { Breadcrumbs, ButtonLink, JourneyCTA, PageHero, SafariCard, SectionHeading, TextLink } from '../components/UI'
import { destinations, safaris } from '../lib/data'
import { NotFoundPage } from './Editorial'

export function DestinationsPage() {
  return <><PageHero eyebrow="THIS IS OUR PART OF THE WORLD" title="Four countries." italic="A thousand ways to feel alive." text="From the mist of the mountains to the magic of the plains. Discover the places we love, with the people who know them best." image="/images/rwanda.jpg" /><section className="section-pad"><div className="container"><SectionHeading eyebrow="WHERE THE JOURNEY TAKES YOU" title="One extraordinary region." italic="Endlessly different." description="Each country has a character all its own. Follow the one that speaks to you — or weave a few together." /><div className="destination-editorial-grid">{destinations.map((destination, index) => <article className="destination-editorial-card" key={destination.slug}><Link className="destination-editorial-image" to={`/destinations/${destination.slug}`}><img src={destination.image} alt={`Discover ${destination.name}`} loading="lazy" /><span>0{index + 1}</span><div><MapPin size={15} />{destination.label}</div></Link><div className="destination-editorial-copy"><div><h2>{destination.name}</h2><Link to={`/destinations/${destination.slug}`} aria-label={`Explore ${destination.name}`} className="circle-link"><ArrowUpRight size={24} /></Link></div><h3>{destination.tagline}</h3><p>{destination.description}</p><TextLink to={`/destinations/${destination.slug}`}>A little closer to {destination.name}</TextLink></div></article>)}</div></div></section><div className="cross-country-note container"><Compass size={34} strokeWidth={1} /><div><h3>No need to choose just one.</h3><p>A gorilla encounter in Uganda. A few days on Kenya’s plains. We can bring your favourite places together in one beautifully considered journey.</p></div><ButtonLink to="/plan-your-safari" variant="outline">Connect the dots</ButtonLink></div><JourneyCTA /></>
}

export function DestinationDetailPage() {
  const { slug } = useParams()
  const destination = destinations.find((item) => item.slug === slug)
  if (!destination) return <NotFoundPage />
  const journeys = safaris.filter((safari) => safari.country.includes(destination.name))
  return <><PageHero eyebrow={destination.label} title={destination.name + ','} italic={destination.tagline} image={destination.image} className="destination-detail-hero"><ButtonLink to={`/safaris?destination=${destination.name}`}>Explore {destination.name} journeys</ButtonLink></PageHero><Breadcrumbs items={[{ label: 'Destinations', to: '/destinations' }, { label: destination.name }]} /><section className="container destination-intro section-pad"><div><p className="eyebrow"><span />A PLACE TO FEEL, NOT JUST TO SEE</p><h2>A little closer<br /><em>to {destination.name}.</em></h2></div><div><p className="lead-copy">{destination.description}</p><p>Travel here with an open mind and a little time to spare. There is a quiet magic in the unexpected moments, and our journeys are designed to leave room for them.</p></div></section><section className="destination-highlights section-pad"><div className="container"><SectionHeading eyebrow="GET TO KNOW THE LANDSCAPE" title="Places that stay" italic="with you." /><div className="place-grid">{destination.places.map((place, index) => <div key={place.name}><span className="place-number">0{index + 1}</span><MapPin size={23} strokeWidth={1.2} /><h3>{place.name}</h3><p>{place.text}</p></div>)}</div></div></section><section className="container seasonal-section section-pad"><div><Sun size={33} strokeWidth={1.1} /><p className="eyebrow">A NOTE ON TIMING</p><h2>Let the seasons<br /><em>shape the story.</em></h2></div><div><p className="lead-copy">{destination.season}</p><p>Tell us what you hope to experience and when you can travel. We’ll help you find a considered balance between the two. Conditions and availability are always checked during detailed planning.</p><TextLink to={`/plan-your-safari?destination=${destination.name}`}>Let’s talk about your dates</TextLink></div></section><section className="related-section section-pad"><div className="container"><SectionHeading eyebrow={`YOUR ${destination.name.toUpperCase()} STORY STARTS HERE`} title="A few beautiful" italic="possibilities." link={{ to: `/safaris?destination=${destination.name}`, text: `All ${destination.name} journeys` }} /><div className={`safari-grid ${journeys.length < 3 ? 'safari-grid-two' : ''}`}>{journeys.map((safari) => <SafariCard safari={safari} key={safari.slug} />)}</div><p className="collection-note"><Leaf size={14} />Every journey can be reimagined, just for you.</p></div></section><JourneyCTA /></>
}
