import { useState, type FormEvent } from 'react'
import { ArrowRight, ArrowUpRight, Compass, HeartHandshake, Leaf, MapPin, Play, ShieldCheck, Sparkles, TreePine, Users } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { destinations, experiences, safaris, stories } from '../lib/data'
import { useSite } from '../lib/site-store'
import { AcaciaMark, ButtonLink, JourneyCTA, SafariCard, ScrollCue, SectionHeading, TextLink } from '../components/UI'

function SafariFinder() {
  const [country, setCountry] = useState('')
  const [experience, setExperience] = useState('')
  const [duration, setDuration] = useState('')
  const navigate = useNavigate()
  function search(event: FormEvent) {
    event.preventDefault()
    const params = new URLSearchParams()
    if (country) params.set('destination', country)
    if (experience) params.set('experience', experience)
    if (duration) params.set('duration', duration)
    navigate(`/safaris${params.size ? `?${params.toString()}` : ''}`)
  }
  return <div className="finder-wrap"><form className="safari-finder container" onSubmit={search}><div className="finder-intro"><Compass size={27} strokeWidth={1.3} /><span>Your adventure.<br /><strong>Your way.</strong></span></div><label><span>WHERE CALLS TO YOU?</span><select aria-label="Choose your destination" value={country} onChange={(event) => setCountry(event.target.value)}><option value="">All destinations</option>{destinations.map((destination) => <option key={destination.slug}>{destination.name}</option>)}</select></label><label><span>WHAT MOVES YOU?</span><select aria-label="Choose your experience" value={experience} onChange={(event) => setExperience(event.target.value)}><option value="">Every kind of wonder</option><option>Gorilla trekking</option><option>Wildlife safari</option><option>Family & slow travel</option><option>Private adventure</option></select></label><label className="finder-duration"><span>HOW LONG DO YOU HAVE?</span><select aria-label="Choose your trip length" value={duration} onChange={(event) => setDuration(event.target.value)}><option value="">Time to explore</option><option value="short">Up to 7 days</option><option value="medium">8–10 days</option><option value="long">11 days or more</option></select></label><button className="button button-primary" type="submit">Find my safari<ArrowRight size={17} /></button></form></div>
}

export function HomePage() {
  const { setFilmOpen } = useSite()
  return <>
    <section className="home-hero"><img className="home-hero-image" src="/images/hero-safari.webp" alt="An elephant family walking across a golden East African savannah beneath an acacia tree" fetchPriority="high" /><div className="hero-shade" /><div className="container hero-content"><p className="eyebrow hero-eyebrow"><span />UNSCRIPTED. UNFORGETTABLE. UNIQUELY YOURS.</p><h1>Africa, in its<br /><em>truest form.</em></h1><p className="hero-description">Extraordinary wildlife. Meaningful connections.<br />Private journeys that bring you a little closer.</p><div className="hero-actions"><ButtonLink to="/safaris">Find your wild</ButtonLink><button className="film-button" onClick={() => setFilmOpen(true)}><span><Play size={13} fill="currentColor" /></span>Feel the Kibira spirit</button></div></div><div className="container hero-bottom"><ScrollCue /><span className="hero-coordinate"><MapPin size={13} />EAST AFRICA<span>01° S · 35° E</span></span><div className="hero-slide"><span>01</span><i /><span>THE WILD IS CALLING</span></div></div></section>
    <SafariFinder />
    <section className="promise-strip"><div className="container"><span><Compass size={20} strokeWidth={1.2} />Local hearts. Insider knowledge.</span><i /><span><Sparkles size={20} strokeWidth={1.2} />Never off-the-shelf. Always you.</span><i /><span><Leaf size={20} strokeWidth={1.2} />Good for you. Better for the wild.</span></div></section>
    <section className="intro-section section-pad" id="discover"><div className="container intro-grid"><div className="intro-heading"><p className="eyebrow"><span />THIS IS KIBIRA</p><h2>Not just a place you go.<br /><em>A feeling you take home.</em></h2><div className="small-line" /><p className="intro-caption">Born in East Africa. Made personal.</p></div><div className="intro-copy"><p>Somewhere between the hush of a rainforest and the endless African sky, something shifts. You slow down. Look closer. Feel more.</p><p>We bring you there. With local insight, a lighter footprint, and a journey shaped entirely around you — from a first encounter with mountain gorillas to the simple joy of a sunset in the bush.</p><TextLink to="/about">Get to know Kibira</TextLink></div><AcaciaMark className="intro-tree" /></div></section>
    <section className="featured-section section-pad"><div className="container"><SectionHeading eyebrow="A LITTLE INSPIRATION" title="Extraordinary journeys." italic="Entirely your own." description="A few of our favourite ways to experience East Africa. Every one is just the beginning." link={{ to: '/safaris', text: 'Explore all safaris' }} /><div className="safari-grid">{safaris.slice(0, 3).map((safari) => <SafariCard key={safari.slug} safari={safari} />)}</div><p className="collection-note"><span />No two travellers are the same. Your safari shouldn’t be either.<span /></p></div></section>
    <section className="destinations-section section-pad"><div className="container"><SectionHeading eyebrow="FOUR COUNTRIES. COUNTLESS POSSIBILITIES." title="Where will your curiosity" italic="take you?" link={{ to: '/destinations', text: 'Discover East Africa' }} /><div className="destination-grid">{destinations.map((destination, index) => <Link className="destination-tile" key={destination.slug} to={`/destinations/${destination.slug}`}><img src={destination.image} alt={destination.name === 'Uganda' ? 'Mountain gorilla in Uganda’s rainforest' : `Wild landscapes of ${destination.name}`} loading="lazy" /><div className="destination-tile-shade" /><span className="destination-number">0{index + 1}</span><div className="destination-tile-bottom"><p>{destination.label}</p><div><h3>{destination.name}</h3><span className="destination-arrow"><ArrowUpRight size={23} /></span></div></div></Link>)}</div></div></section>
    <section className="experience-spotlight"><div className="experience-photo"><img src="/images/gorilla.jpg" alt="An intimate view of a mountain gorilla in the forest" loading="lazy" /><span><MapPin size={13} />BWINDI IMPENETRABLE FOREST, UGANDA</span></div><div className="experience-story"><p className="eyebrow"><span />SOME MOMENTS CHANGE EVERYTHING</p><h2>A world away.<br /><em>A connection<br />like no other.</em></h2><p>One quiet hour in the company of mountain gorillas. A shared glance. A familiar gesture. An extraordinary reminder of how connected we really are.</p><p>Step into their world, gently.</p><TextLink to="/experiences/gorilla-trekking" light>Discover gorilla trekking</TextLink><Leaf className="story-leaf" size={190} strokeWidth={.45} /></div></section>
    <section className="values-section section-pad"><div className="container"><SectionHeading eyebrow="THE KIBIRA DIFFERENCE" title="Big on wonder." italic="Thoughtful in every detail." centered /><div className="values-grid">{[{ icon: Compass, title: 'Guided by local hearts', text: 'The backroads. The hidden viewpoints. The stories only a local can tell. See East Africa through the people who call it home.' }, { icon: Users, title: 'Made for you, not everyone', text: 'Your pace, your passions, your people. We listen first, then bring every detail together in a safari that feels unmistakably yours.' }, { icon: Leaf, title: 'Wild places, cared for', text: 'Respect for wildlife. Genuine community connections. Thoughtful choices that make your journey feel good in every sense.' }, { icon: HeartHandshake, title: 'The little things matter', text: 'A warm welcome. A perfectly timed pause. A guide who notices. It is the care you feel, not just the things you see.' }].map((value) => <div key={value.title}><value.icon size={31} strokeWidth={1} /><h3>{value.title}</h3><p>{value.text}</p></div>)}</div><div className="center"><TextLink to="/conservation">A more meaningful way to travel</TextLink></div></div></section>
    <section className="experience-collection section-pad"><div className="container"><SectionHeading eyebrow="FOLLOW YOUR SENSE OF WONDER" title="How do you want to" italic="feel the wild?" link={{ to: '/experiences', text: 'Find your experience' }} /><div className="experience-small-grid">{experiences.slice(1).map((experience) => <Link to={`/experiences/${experience.slug}`} key={experience.slug}><div><img src={experience.image} alt={experience.shortTitle} loading="lazy" /><span><ArrowUpRight size={22} /></span></div><p>{experience.eyebrow}</p><h3>{experience.shortTitle}</h3></Link>)}</div></div></section>
    <section className="lodges-feature section-pad"><div className="container lodge-split"><div className="lodge-image"><img src="/images/lodge.jpg" alt="Intimate safari lodges tucked into a natural rocky landscape" loading="lazy" /><div className="lodge-image-caption"><TreePine size={16} /><span>A sense of place. A feeling of home.</span></div></div><div className="lodge-copy"><p className="eyebrow"><span />STAY SOMEWHERE THAT STAYS WITH YOU</p><h2>Wild outside.<br /><em>Wonderful within.</em></h2><p>Forest-edge hideaways. Beautifully simple tented camps. A veranda with a view you’ll never quite forget.</p><p>We choose places for how they make you feel — and the care they show the world around them.</p><TextLink to="/lodges">Discover our kind of stay</TextLink></div></div></section>
    <section className="planning-strip"><div className="container"><div className="planning-strip-title"><p className="eyebrow">FROM A LITTLE IDEA TO A BIG ADVENTURE</p><h2>Beautifully simple.<br /><em>From the very beginning.</em></h2></div><div className="planning-step"><span>01</span><h3>Tell us your dream</h3><p>A destination, a feeling, a wild idea.<br />We’re all ears.</p></div><div className="planning-step"><span>02</span><h3>Make it your own</h3><p>We shape the details together.<br />Until it feels just right.</p></div><div className="planning-step"><span>03</span><h3>Be here. Fully.</h3><p>Leave the logistics behind.<br />Let the journey unfold.</p></div></div></section>
    <section className="journal-section section-pad"><div className="container"><SectionHeading eyebrow="NOTES FROM THE WILD" title="Stories to stir" italic="your sense of adventure." link={{ to: '/stories', text: 'Open the journal' }} /><div className="journal-grid">{stories.map((story) => <article className="journal-card" key={story.slug}><Link to={`/stories/${story.slug}`} className="journal-image"><img src={story.image} alt={story.title} loading="lazy" /><span><ArrowUpRight size={22} /></span></Link><div className="journal-meta">{story.category}<span>{story.readTime}</span></div><Link to={`/stories/${story.slug}`}><h3>{story.title}</h3></Link></article>)}</div></div></section>
    <div className="final-promise container"><ShieldCheck size={20} strokeWidth={1.3} /><p>Your journey. Thoughtfully considered, from first hello to the way home.</p></div>
    <JourneyCTA />
  </>
}
